name: "Prayer Times"
description: "Islamic Prayer Times add-on"
version: "1.3.3"
slug: prayer-times
url: "https://github.com/besanur/homeassistant-addons/tree/main/prayer-times"
arch:
  - amd64
  - aarch64
ports:
  1453/tcp: 1453
ports_description:
  1453/tcp: Prayer Times API
image: "ghcr.io/besanur/prayer-times-{arch}"
